# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrators',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
