# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admina', '0002_administrators_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrators',
            name='is_use',
            field=models.BooleanField(default=True),
        ),
    ]
